import { zodResolver } from '@hookform/resolvers/zod';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { signOut } from 'firebase/auth';
import { Controller, useForm } from 'react-hook-form';
import { useEffect, useLayoutEffect, useState } from 'react';
import { Alert, ScrollView, StyleSheet, View } from 'react-native';
import { ActivityIndicator, Button, Divider, HelperText, Surface, Text, TextInput } from 'react-native-paper';

import { auth } from '../../../app/config/firebase';
import { GoalsSummary } from '../components/GoalsSummary';
import { ProfileAvatar } from '../components/ProfileAvatar';
import { useProfile } from '../hooks/useProfile';
import { profileSchema, type ProfileFormValues } from '../schemas/profileSchema';
import type { ProfileInput, ProfileStackParamList } from '../types';

type Props = NativeStackScreenProps<ProfileStackParamList, 'Profile'>;

export function ProfileScreen({ navigation }: Props) {
  const user = auth.currentUser;
  const { profile, isLoading, error, save } = useProfile(user?.uid, user?.email, user?.displayName);
  const [isSaving, setIsSaving] = useState(false);
  const { control, handleSubmit, formState: { errors }, reset } = useForm<ProfileFormValues>({ resolver: zodResolver(profileSchema) as never });
  useLayoutEffect(() => { navigation.setOptions({ title: 'Profile' }); }, [navigation]);
  useEffect(() => { if (profile) reset({ displayName: profile.displayName, avatarUrl: profile.avatarUrl ?? '', heightCm: profile.heightCm, ...profile.goals }); }, [profile, reset]);
  const onSave = async (values: ProfileFormValues) => { setIsSaving(true); try { const { steps, calories, waterMl, sleepHours, workoutMinutesWeekly, targetWeightKg, ...identity } = values; const input: ProfileInput = { ...identity, goals: { steps, calories, waterMl, sleepHours, workoutMinutesWeekly, targetWeightKg } }; await save(input); Alert.alert('Profile updated', 'Your details and goals have been saved.'); } catch (saveError) { Alert.alert('Could not save profile', saveError instanceof Error ? saveError.message : 'Try again shortly.'); } finally { setIsSaving(false); } };
  const onLogout = () => Alert.alert('Log out?', 'You can sign back in at any time.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Log out', style: 'destructive', onPress: () => void signOut(auth) }]);
  if (isLoading || !profile) return <View style={styles.center}><ActivityIndicator size="large" /></View>;
  return <ScrollView style={styles.container} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><ProfileAvatar name={profile.displayName} avatarUrl={profile.avatarUrl} /><Text variant="headlineSmall" style={styles.name}>{profile.displayName}</Text><Text style={styles.email}>{profile.email}</Text></View><GoalsSummary goals={profile.goals} /><Surface elevation={1} style={styles.formCard}><Text variant="titleMedium" style={styles.title}>Edit profile</Text><Controller control={control} name="displayName" render={({ field: { value, onChange } }) => <TextInput label="Display name" mode="outlined" value={value ?? ''} onChangeText={onChange} error={Boolean(errors.displayName)} />} /><HelperText type="error" visible={Boolean(errors.displayName)}>{errors.displayName?.message}</HelperText><Controller control={control} name="avatarUrl" render={({ field: { value, onChange } }) => <TextInput label="Avatar image URL (optional)" mode="outlined" value={value ?? ''} onChangeText={onChange} error={Boolean(errors.avatarUrl)} />} /><HelperText type="error" visible={Boolean(errors.avatarUrl)}>{errors.avatarUrl?.message}</HelperText><Controller control={control} name="heightCm" render={({ field: { value, onChange } }) => <TextInput label="Height (cm)" mode="outlined" keyboardType="number-pad" value={value?.toString() ?? ''} onChangeText={onChange} error={Boolean(errors.heightCm)} />} /><HelperText type="error" visible={Boolean(errors.heightCm)}>{errors.heightCm?.message}</HelperText><Divider style={styles.divider} /><Text variant="titleMedium" style={styles.title}>Goal settings</Text><GoalInput control={control} name="steps" label="Daily steps" error={errors.steps?.message} /><GoalInput control={control} name="calories" label="Daily calories (kcal)" error={errors.calories?.message} /><GoalInput control={control} name="waterMl" label="Daily water (ml)" error={errors.waterMl?.message} /><GoalInput control={control} name="sleepHours" label="Sleep goal (hours)" error={errors.sleepHours?.message} /><GoalInput control={control} name="workoutMinutesWeekly" label="Weekly workout (minutes)" error={errors.workoutMinutesWeekly?.message} /><GoalInput control={control} name="targetWeightKg" label="Target weight (kg, optional)" error={errors.targetWeightKg?.message} /><Button mode="contained" style={styles.save} contentStyle={styles.saveContent} loading={isSaving} disabled={isSaving} onPress={handleSubmit(onSave)}>Save profile</Button></Surface>{error ? <Text style={styles.error}>{error}</Text> : null}<Button mode="outlined" textColor="#B3261E" style={styles.logout} icon="logout" onPress={onLogout}>Log out</Button></ScrollView>;
}
function GoalInput({ control, name, label, error }: { control: ReturnType<typeof useForm<ProfileFormValues>>['control']; name: keyof Pick<ProfileFormValues, 'steps' | 'calories' | 'waterMl' | 'sleepHours' | 'workoutMinutesWeekly' | 'targetWeightKg'>; label: string; error?: string }) { return <><Controller control={control} name={name} render={({ field: { value, onChange } }) => <TextInput label={label} mode="outlined" keyboardType="decimal-pad" value={value?.toString() ?? ''} onChangeText={onChange} error={Boolean(error)} />} /><HelperText type="error" visible={Boolean(error)}>{error}</HelperText></>; }
const styles = StyleSheet.create({ container: { backgroundColor: '#FAF9FF', flex: 1 }, content: { padding: 20, paddingBottom: 36 }, center: { alignItems: 'center', flex: 1, justifyContent: 'center' }, header: { alignItems: 'center', paddingTop: 10 }, name: { fontWeight: '800', marginTop: 10 }, email: { color: '#77727E', marginTop: 3 }, formCard: { borderRadius: 24, marginTop: 16, padding: 20 }, title: { fontWeight: '800', marginBottom: 14 }, divider: { marginVertical: 20 }, save: { borderRadius: 16, marginTop: 12 }, saveContent: { minHeight: 52 }, logout: { borderColor: '#E5B9B9', borderRadius: 16, marginTop: 18 }, error: { color: '#B3261E', marginTop: 12, textAlign: 'center' } });
